# Base configs
baseurl: "https://giterotic.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by GitErotic"
subtitle: "Revolutionizing erotic photography in the digital age"
author: "GitErotic Team"
header:
 title: "Photography"
 subtitle: "by GitErotic"
footer:
 name: "We are GitErotic."
 bio: "Our professional team captures the most elusive qualities of human form.  We strive to highlight your perfection every time."
 github: "Embrace your perfect form with our state of the art erotic production.  Full packages start at just $250.  New clients receive 30 minutes and 5 professionally produced digital photos for free. Locations in 39 U.S. states.  Contact us here for pricing and information about our photography or to arrange a photo shoot."
